name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    
      - name: Install OCI CLI
        run: |
          pip install oci-cli

     
      - name: Create OCI private key
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > /home/runner/.oci/oci_api_key.pem
          chmod 600 /home/runner/.oci/oci_api_key.pem

     
      - name: Configure OCI CLI
        env:
          OCI_CONFIG_CONTENT: ${{ secrets.OCI_CONFIG }}
        run: |
          mkdir -p ~/.oci
          echo "$OCI_CONFIG_CONTENT" > ~/.oci/config

    
      - name: Set up kubeconfig for Oracle cluster
        run: |
          mkdir -p $HOME/.kube
          oci ce cluster create-kubeconfig \
            --cluster-id ${{ secrets.OCI_CLUSTER_ID }} \
            --kubeconfig $HOME/.kube/config \
            --region ${{ secrets.OCI_REGION }} \
            --token-version 2.0.0 \
            --kube-endpoint PUBLIC_ENDPOINT

    
      - name: Deploy manifests to cluster
        run: |
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod
